services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shingul_backend
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3333

      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shingul
      DB_PASSWORD: herbBoss
      DB_DATABASE: shingul_dev

      # Redis (for BullMQ / Transmit backplanes / caching, etc.)
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD: "test"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: shingul_worker
    command: ["sh", "-c", "node ace run:game-worker"]
    environment:
      NODE_ENV: development
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shingul
      DB_PASSWORD: herbBoss
      DB_DATABASE: shingul_dev

      REDIS_HOST: redis
      REDIS_PORT: 6379
      # REDIS_PASSWORD: ""
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  postgres:
    image: postgres:16-alpine
    container_name: shingul_db
    environment:
      POSTGRES_USER: shingul
      POSTGRES_PASSWORD: herbBoss
      POSTGRES_DB: shingul_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shingul -d shingul_dev"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: shingul_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  redisinsight:
    image: redis/redisinsight:latest
    container_name: shingul_redisinsight
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - redisinsightdata:/data

volumes:
  pgdata:
  redisdata:
  redisinsightdata:
